### ISSUE TITLE
Checklist after move to `renovatebot` organization

### ISSUE THREAD

**Issue by HonkingGoose** [HonkingGoose/vale-plain-language-guidelines#18]
Todo:

- [ ] Check references to `HonkingGoose` and `honkinggoose`, and update them if needed
- [ ] Update branch protection rules for `main`
- [ ] Check bot configuration
- [ ] Check Renovate bot configuration (`renovate.json`)
- [ ] Extend Renovate bot config from `renovatebot/.github`
- [ ] Setup GitHub Merge Queue so it works with this repository
- [ ] Check permissions
- [ ] Invite collaborators
- [ ] Add more `CODEOWNERS`
- [ ] Check CI files
- [ ] Check permissions on CI files
- [ ] Check GitHub App integrations

**Comment by HonkingGoose** [comment]
I no longer intend to use Vale on our Renovate repositories. So I'm closing this issue as not planned.
